/**
 * Created by wangdi on 23/11/16.
 */
'use strict';

export const FETCH_HOME_DATA_SUCCESS = 'FETCH_HOME_DATA_SUCCESS';
export const FETCH_HOME_DATA_FAILURE = 'FETCH_HOME_DATA_FAILURE';
export const FETCH_HOME_DATE_REQUEST = 'FETCH_HOME_DATE_REQUEST';

export const FETCH_RANDOM_DATA_SUCCESS = 'FETCH_RANDOM_DATA_SUCCESS';
export const FETCH_RANDOM_DATA_FAILURE = 'FETCH_RANDOM_DATA_FAILURE';
export const FETCH_RANDOM_DATA_REQUEST = 'FETCH_RANDOM_DATA_REQUEST';
export const FETCH_RANDOM_MORE_DATA_SUCCESS = 'FETCH_RANDOM_MORE_DATA_SUCCESS';
export const FETCH_RANDOM_MORE_DATA_REQUEST = 'FETCH_RANDOM_MORE_DATA_REQUEST';
export const FETCH_RANDOM_MORE_DATA_FAILURE = 'FETCH_RANDOM_MORE_DATA_FAILURE';

export const FETCH_CATEGORY_DATA_SUCCESS = 'FETCH_CATEGORY_DATA_SUCCESS';
export const FETCH_CATEGORY_DATA_FAILURE = 'FETCH_CATEGORY_DATA_FAILURE';
export const FETCH_CATEGORY_DATA_REQUEST = 'FETCH_CATEGORY_DATA_REQUEST';
export const FETCH_CATEGORY_MORE_DATA_REQUEST = 'FETCH_CATEGORY_MORE_DATA_REQUEST';
export const FETCH_CATEGORY_MORE_DATA_FAILURE = 'FETCH_CATEGORY_MORE_DATA_FAILURE';
export const FETCH_CATEGORY_DATA_IS_FULL = 'FETCH_CATEGORY_DATA_IS_FULL';

export const UPDATE_STAR_LIST = 'UPDATE_STAR_LIST';
export const STAR_DATA_SUCCESS = 'STAR_DATA_SUCCESS';
export const UNSTAR_DATA_SUCCESS = 'UNSTAR_DATA_SUCCESS';
export const UPDATE_STAR_STATE = 'UPDATE_STAR_STATE';

export const CHANGE_COLOR = 'CHANGE_COLOR';
export const CHANGE_DISPLAY_ORDER = 'CHANGE_DISPLAY_ORDER';
export const OPEN_SHOW_THUMBNAIL = 'OPEN_SHOW_THUMBNAIL';
export const CLOSE_SHOW_THUMBNAIL = 'CLOSE_SHOW_THUMBNAIL';
export const OPEN_NIGHT_MODE = 'OPEN_NIGHT_MODE';
export const CLOSE_NIGHT_MODE = 'CLOSE_NIGHT_MODE';
export const OPEN_AUTO_FETCH = 'OPEN_AUTO_FETCH';
export const CLOSE_AUTO_FETCH = 'CLOSE_AUTO_FETCH';

//用户登录/注册
export const PERFORM_LOGIN_ACTION = 'PERFORM_LOGIN_ACTION';  
export const RECEIVE_LOGIN_ACTION = 'RECEIVE_LOGIN_ACTION';
export const PECOUT_LOGIN_ACTION = 'RECOUT_LOGIN_ACTION';
export const PERFORM_LOGIN_ERROR = 'PERFORM_LOGIN_ERROR';
export const FETCH_KEY_ACTION = 'FETCH_KEY_ACTION';

//缓存相关
export const GET_CACHE_SIZE = 'GET_CACHE_SIZE';
//游戏数据版本 怀旧版/圣灵版
export const GAME_DATA_VERSION = 'GAME_DATA_VERSION';

//游戏物品列表
export const FETCH_ITEM_DATA_SUCCESS = 'FETCH_ITEM_DATA_SUCCESS';
export const FETCH_ITEM_DATA_FAILURE = 'FETCH_ITEM_DATA_FAILURE';
export const FETCH_ITEM_DATA_EMPTY = 'FETCH_ITEM_DATA_EMPTY';
export const FETCH_ITEM_DATA_REQUEST = 'FETCH_ITEM_DATA_REQUEST';
export const FETCH_ITEM_MORE_DATA_REQUEST = 'FETCH_ITEM_MORE_DATA_REQUEST';
export const FETCH_ITEM_MORE_DATA_FAILURE = 'FETCH_ITEM_MORE_DATA_FAILURE';
export const FETCH_ITEM_DATA_IS_FULL = 'FETCH_ITEM_DATA_IS_FULL';
export const SELECT_ITEM_ROWDATA = 'SELECT_ITEM_ROWDATA';
export const SELECT_ITEM_SEND = 'SELECT_ITEM_SEND';

//发送物品相关
export const PERFORM_SEND_ITEM_ACTION = 'PERFORM_SEND_ITEM_ACTION';  
export const RECEIVE_SEND_ITEM_ACTION = 'RECEIVE_SEND_ITEM_ACTION';
export const PERFORM_SEND_ITEM_ERROR = 'PERFORM_SEND_ITEM_ERROR';
export const RECEIVE_SERVER_LIST_ACTION = 'RECEIVE_SERVER_LIST_ACTION';

//搜索记录相关
export const UPDATE_SEARCH_LIST = 'UPDATE_SEARCH_LIST';
export const SEARCH_DATA_SUCCESS = 'SEARCH_DATA_SUCCESS';
export const UNSEARCH_DATA_SUCCESS = 'UNSEARCH_DATA_SUCCESS';
export const UPDATE_SEARCH_STATE = 'UPDATE_SEARCH_STATE';
export const UPDATE_SEARCH_INPUT = 'UPDATE_SEARCH_INPUT';